name: lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install ruff (if config present)
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run ruff (skip if no config)
        run: |
          if [ -f ruff.toml ] || [ -f pyproject.toml ]; then
            ruff --version
            # Run lint but do not fail CI initially; tighten later
            ruff check app || true
          else
            echo "No ruff config; skipping lint"
          fi
