name: build-and-release

on:
  push:
    tags:
      - 'v*'

# Ensure the GITHUB_TOKEN has permission to create releases
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CERT_PFX_B64: ${{ secrets.CERT_PFX }}
      CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller Flask Flask-SocketIO python-engineio python-socketio python-osc jinja2
      - name: Build artifacts
        run: |
          pyinstaller --clean --noconfirm main.spec
      - name: Zip GUI onefile
        if: always()
        shell: pwsh
        run: |
          if (Test-Path dist/GamepadOSCMapper-GUI.exe) {
            $zipName = "GamepadOSCMapper-GUI-$env:GITHUB_REF_NAME-win64.zip"
            if ($env:GITHUB_REF_NAME -eq $null -or $env:GITHUB_REF_NAME -eq '') { $zipName = "GamepadOSCMapper-GUI-win64.zip" }
            Compress-Archive -Path dist/GamepadOSCMapper-GUI.exe -DestinationPath dist/$zipName -Force
          }
      - name: Zip CLI onefile
        if: always()
        shell: pwsh
        run: |
          if (Test-Path dist/GamepadOSCMapper-CLI-OneFile.exe) {
            $zipName = "GamepadOSCMapper-CLI-OneFile-$env:GITHUB_REF_NAME-win64.zip"
            if ($env:GITHUB_REF_NAME -eq $null -or $env:GITHUB_REF_NAME -eq '') { $zipName = "GamepadOSCMapper-CLI-OneFile-win64.zip" }
            Compress-Archive -Path dist/GamepadOSCMapper-CLI-OneFile.exe -DestinationPath dist/$zipName -Force
          }
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GamepadOSCMapper-win
          path: |
            dist/GamepadOSCMapper-GUI-*-win64.zip
            dist/GamepadOSCMapper-CLI-OneFile-*-win64.zip

  release:
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: GamepadOSCMapper-win
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/GamepadOSCMapper-GUI-*-win64.zip
            dist/GamepadOSCMapper-CLI-OneFile-*-win64.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


